Initial gget version
vliubezny/gget pull request #1
Opened 2020-12-01 21:32 UTC by vliubezny

Usage example:
```
$ ./gget https://github.com/tenntenn/gopher-stickers/raw/master/png/angry.png \
https://github.com/tenntenn/gopher-stickers/raw/master/png/beer.png \
HTTPS://github.com/tenntenn/gopher-stickers/raw/master/png/hi.png
angry.png   beer.png   hi.png   
0%          0%         14%      
0%          0%         28%      
0%          0%         43%      
0%          0%         57%      
0%          0%         72%      
0%          0%         86%      
0%          0%         100%     
0%          16%        100%     
0%          33%        100%     
0%          50%        100%     
0%          67%        100%     
0%          84%        100%     
0%          100%       100%     
13%         100%       100%     
26%         100%       100%     
39%         100%       100%     
52%         100%       100%     
65%         100%       100%     
79%         100%       100%     
92%         100%       100%     
100%        100%       100%
```

2020-12-06 19:11 UTC, mikluke requested changes

2020-12-06 19:11 UTC, mikluke commented on loader.go
> +	counter    int64
Очевиднее было бы downloaded или processed

2020-12-06 19:11 UTC, mikluke commented on loader.go
> +		pn.progressCh <- ProgressNotAvailable
В этом случае нам достаточно единожды отправить такое состояние (читай создавать райтер только тогда, когда известен размер)

2020-12-06 19:11 UTC, mikluke commented on loader.go
> +		if err != nil {
Я бы заинлайнил

2020-12-06 19:11 UTC, mikluke commented on loader_test.go
> +		t.Run(fmt.Sprintf("Total: %d", c.total), func(t *testing.T) {
👍

2020-12-06 19:11 UTC, mikluke commented on loader_test.go
> +			assert.Equalf(t, len(bytes), n, "Invalid n")
При очевидном именовании переменных лучше не юзать форматированный тест

2020-12-06 19:11 UTC, mikluke commented on loader_test.go
> +	assert.Equal(t, 100.0, progress, "Download is not completed")
Проверь кейс с ошибкой и n/a

2020-12-06 19:11 UTC, mikluke commented on main.go
> +func terminate(message string) {
Наверное нет смысла экономить на двух строчках, добавляя 3 новых в файл

2020-12-06 19:11 UTC, mikluke commented on main.go
> +		terminate("Canceled")
Добавь логгер и вызывай fatal

2020-12-06 19:11 UTC, mikluke commented on main.go
> +	progressChannels := make(map[string]<-chan float64)
У тебя заранее известен размер

2020-12-06 19:11 UTC, mikluke commented on main.go
> +		filePath := filepath.Base(fileURL)
Я бы не создал дор переменную, функция не сильно длинная, а очевидности коду не сильно добавит

2020-12-06 19:11 UTC, mikluke commented on main.go
> +	if len(u.EscapedPath()) <= 1 {
Не имеет особо смысла, файл может и с главной раздаваться (или качаешь страницу)

2020-12-06 19:11 UTC, mikluke commented on view.go
> +var tw *tabwriter.Writer
Mutable global var, никогда так не делай

2020-12-06 19:11 UTC, mikluke commented on view.go
> +func observeStatus(progressChannels map[string]<-chan float64) error {
Не кажется функция слишком сложной?

2020-12-06 19:11 UTC, mikluke commented on view.go
> +	for filePath, progressCh := range progressChannels {
Не особо читаемо вышло

2020-12-06 19:11 UTC, mikluke commented on view.go
> +	for filePath, progressCh := range progressChannels {
В мейне мапу состояний сделай, при запуске скачки сразу запусти рутину, которая будет изменять состояние. Дальше просто отрисовывай мапу

2020-12-06 19:11 UTC, mikluke commented on view.go
> +func printTable(headers []string, state *sync.Map) error {
Более аккуратным решением выглядит

'''
type state struct {
  m sync.Mutex
  s map[string]float64
}

func(s *state) print()
func(s *state) set(k string, v float64)
'''

Или что-то вроде. Можно стрингер реализовать и просто выводить таблицу

2020-12-06 19:11 UTC, mikluke commented on view.go
> +			fmt.Fprintf(tw, "Download error\t")
Просто err, или вместо na not available

2020-12-06 19:11 UTC, mikluke commented on view.go
> +		case <-done:
Выпилив саму отрисовку в отдельную функцию, тебе не понадобится делать вот так. В конце программы просто выведешь в последний раз результат

2020-12-06 19:11 UTC, mikluke commented on view.go
> +func moveCursorBeforeTable() {
Уйдёт в функцию print

2020-12-06 19:11 UTC, mikluke commented on view_test.go
> +func TestPrintTable(t *testing.T) {
Тест должен выглядеть проще

2020-12-06 19:11 UTC, mikluke commented on view_test.go
> +func TestPrintTable(t *testing.T) {
То как сетапится тест говорит о неправильном дизайне функции

2020-12-06 19:11 UTC, mikluke commented on main.go
> +		terminate("Canceled")
Надо аккуратно выйти а не как будто sigkill прилетел :)

Используй context

2020-12-07 13:19 UTC, mikluke commented on loader.go
> +	var progress float64 = float64(pn.processed) * 100 / float64(pn.total)
progress := float64(pn.processed) * 100 / float64(pn.total)

но вообще я бы заинлайнил

2020-12-07 13:21 UTC, mikluke commented on loader_test.go
> +	n, err := pn.Write(bytes)
теперь больше похоже на хороший юнит тест

2020-12-07 13:22 UTC, mikluke commented on main.go
> +		log.Fatal(usage)
вот тут конечно лучше не фаталом выходить, это все же хелп просто

2020-12-07 18:14 UTC, merged

2020-12-07 21:40 UTC, vliubezny commented on main.go
> +		log.Fatal(usage)
для unix тулов это довольно обычное поведение - выводить usage при отсутствии аргументов и выходить с ненулевым кодом, например `wget`, `chmod`. так что, думаю, `log.Fatal` тут уместно использовать